### ISSUE TITLE
which version of QT was this written to use?

### ISSUE THREAD

**Issue by bsenftner** [diegomacario/Dyna-Kinematics#1]
I do not have QT on my dev system, and want to try this project out. Trying to install QT, there are many different versions of QT available from their online installer, and installing QT is notoriously slow on Windows. Trying a naive install of multiple versions has my system only at 35% installed after 9+ hours. So, which version should I install?

**Comment by diegomacario** [comment]
Hi Blake! I apologize for not leaving instructions on how to build this project. I shouldn't have shared it before cleaning up the code and writing a makefile, but after working on it for so long I just wanted to ship it! Hehehe

To answer your questions:

- I used Qt version 5.12.6
- The only Qt DLLs that the project uses are: Qt5Core.dll, Qt5Gui.dll and Qt5Widgets.dll.
- So when you install Qt, you don't need to install all the components that it offers (I think that's why your installation has taken so long). I only installed the core and the msvc2017 64-bit component.
- To build the project I used Visual Studio 2019 with the [Qt VS Tools](https://marketplace.visualstudio.com/items?itemName=TheQtCompany.QtVisualStudioTools-19123) for Visual Studio 2019.
- Once you have Qt and the Qt VS Tools installed, make sure to make the Qt VS Tools point to the right version of Qt in Visual Studio:

![Qt_VS_Tools_Options](https://user-images.githubusercontent.com/8304271/86523776-58305100-be3f-11ea-8ddd-1224693da212.PNG)

- And for the "Remember Frames" feature to work, you need to have FFmpeg installed globally on your machine.

I plan to make this process easy by writing a makefile and proper instructions for building the project, but I hope that the information above can help you do it in the meantime.

One thing to note: since the timestep is fixed, the demo simulations might look too fast or too slow on your machine. I plan to add an option to enable/disable the fixed timestep. For now, if a simulation looks too fast or too slow, just adjust the velocity of the bodies in it.

Please let me know if you have any other questions!

**Comment by diegomacario** [comment]
Hi Blake!

Over the last few weeks I have cleaned up this project's the code, gotten it to run on macOS, and added detailed instructions on how to build it [here](https://github.com/diegomacario/Dyna-Kinematics/blob/master/BUILD_INSTRUCTIONS.md).

There is still much that I need to clean up, but at least it should be easy to build this project now, so I'm closing this issue.

Thank you!
